###################################
# SCORES
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: score
  labels:
    app: score
spec:
  replicas: 1
  selector:
    matchLabels:
      app: score
  template:
    metadata:
      labels:
        app: score
    spec:
      containers:
        - name: score
          image: us-central1-docker.pkg.dev/proyectogrupo3/repository-baggage/score:1.0
          ports:
            - containerPort: 3004
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always
          env:
          - name: USERS_PATH
            value: "http://servicio-users"
          - name: POSTS_PATH
            value: "http://servicio-posts"
          - name: OFFERS_PATH
            value: "http://servicio-offers"
          - name: ROUTES_PATH
            value: "http://servicio-routes"
          - name: SCORES_PATH
            value: "http://servicio-scores"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: baggage-score-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3004
    type: HTTP
    requestPath: /score/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-score
  annotations:
    cloud.google.com/backend-config: '{"default": "baggage-score-config"}'
spec:
  type: NodePort
  selector:
    app: score
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3007
      nodePort: 31023

###################################
# RF-005
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf005
  labels:
    app: rf005
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rf005
  template:
    metadata:
      labels:
        app: rf005
    spec:
      containers:
        - name: rf005
          image: us-central1-docker.pkg.dev/proyectogrupo3/repository-baggage/rf005:1.0
          ports:
            - containerPort: 3007
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always
          env:
          - name: USERS_PATH
            value: "http://servicio-users"
          - name: POSTS_PATH
            value: "http://servicio-posts"
          - name: OFFERS_PATH
            value: "http://servicio-offers"
          - name: ROUTES_PATH
            value: "http://servicio-routes"
          - name: SCORES_PATH
            value: "http://servicio-scores"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: baggage-rf005-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3007
    type: HTTP
    requestPath: /rf005/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-rf005
  annotations:
    cloud.google.com/backend-config: '{"default": "baggage-rf005-config"}'
spec:
  type: NodePort
  selector:
    app: rf005
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3007
      nodePort: 31023