INSERT INTO OFFER(POSTID, USERID, DESCRIPTION, SIZE, FRAGILE, OFFER) VALUES('AA001','USER01','PAQUETE PEQUEÑO','SMALL',FALSE,100);
INSERT INTO OFFER(POSTID, DESCRIPTION, SIZE, FRAGILE, OFFER) VALUES('AA001','PAQUETE PEQUEÑO','SMALL',FALSE,100);

