name: Test coverage
on:
  push:
    branches: 
      - main
jobs:
  test_user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./users
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./users
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./users
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
  
  test_post:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./posts
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./posts
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./posts
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70

  test_routes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./routes
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./routes
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./routes
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70

  test_offers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./offers
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./offers
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./offers
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70

  test_score:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./score
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./score
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./score
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70

  test_rf003:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./rf003
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./rf003
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./rf003
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70

  test_rf005:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install pipenv
        working-directory: ./rf005
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./rf005
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./rf005
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70